package model.team;

public enum Channels {
	AUDIO_MM_PS_COMM,
	DATA_PS_PS_COMM,
	AUDIO_PS_MM_COMM,
	DATA_UAVBAT_UAV_COMM,
	AUDIO_MM_VO_COMM,
	DATA_MM_MM_COMM,
	DATA_MM_VGUI_COMM,
	AUDIO_MM_OP_COMM,
	AUDIO_OP_MM_COMM,
	DATA_OP_UAV_COMM,
	DATA_UAVFP_UAV_COMM,
	DATA_UAVFP_OGUI_COMM,
	DATA_OP_OGUI_COMM,
	DATA_OP_OP_COMM,
}
