package model.team;

public enum Channels {
	AUDIO_MM_PS_COMM,
	DATA_PS_PS_COMM,
	AUDIO_PS_MM_COMM,
	AUDIO_MM_VO_COMM,
	DATA_VO_VO_COMM,
	AUDIO_VO_MM_COMM,
	DATA_MM_MM_COMM,
	AUDIO_MM_OP_COMM,
	AUDIO_OP_MM_COMM,
	DATA_OP_OP_COMM,
}
