package model.team;

public enum Channels {
	AUDIO_MM_PS_COMM,
	DATA_PS_PS_COMM,
	AUDIO_PS_MM_COMM,
	DATA_MM_MM_COMM,
	AUDIO_MM_OP_COMM,
	AUDIO_OP_MM_COMM,
	DATA_OP_UAV_COMM,
	DATA_OGUI_UAV_COMM,
	VIDEO_UAV_OP_COMM,
	DATA_UAVFP_UAV_COMM,
	DATA_UAVFP_OGUI_COMM,
	DATA_OP_OGUI_COMM,
	VIDEO_OGUI_OP_COMM,
	DATA_OP_OP_COMM,
}
