PS ParentSearch
OP Operator
MM MissionManager
UAV UAV
VO VideoOperator
OGUI OperatorGui
UAVBAT UAVBattery
UAVFP UAVFlightPlan
UAVVF UAVVideoFeed
VGUI VideoOperatorGui
GUI VideoOperatorGui
UAVHAG UAVHeightAboveGround
UAVS UAVSignal
AL Alice
BO Bob
TP TestPerson
NSE NewSearchEvent